export const studentsList = [
  {
    id: 1,
    username: 'john_doe',
    password: 'password123',
    name: 'John Doe',
    age: 16,
    class: 10,
    marks: {
      math: 50,
      science: 40,
      english: 38,
    },
    totalMarks: 128,
  },
  {
    id: 2,
    username: 'jane_smith',
    password: 'securepass',
    name: 'Jane Smith',
    age: 17,
    class: 9,
    marks: {
      math: 72,
      science: 88,
      english: 65,
    },
    totalMarks: 225,
  },
  {
    id: 3,
    username: 'emily_clark',
    password: 'mypassword',
    name: 'Emily Clark',
    age: 15,
    class: 8,
    marks: {
      math: 95,
      science: 92,
      english: 89,
    },
    totalMarks: 276,
  },
  {
    id: 4,
    username: 'michael_brown',
    password: 'pass123',
    name: 'Michael Brown',
    age: 18,
    class: 12,
    marks: {
      math: 60,
      science: 70,
      english: 58,
    },
    totalMarks: 188,
  },
  {
    id: 5,
    username: 'sophia_wilson',
    password: 'sophiapass',
    name: 'Sophia Wilson',
    age: 16,
    class: 10,
    marks: {
      math: 78,
      science: 84,
      english: 80,
    },
    totalMarks: 242,
  },
  {
    id: 6,
    username: 'daniel_jones',
    password: 'danielpass',
    name: 'Daniel Jones',
    age: 17,
    class: 11,
    marks: {
      math: 88,
      science: 85,
      english: 91,
    },
    totalMarks: 264,
  },
  {
    id: 7,
    username: 'mia_davis',
    password: 'mia1234',
    name: 'Mia Davis',
    age: 15,
    class: 7,
    marks: {
      math: 55,
      science: 60,
      english: 62,
    },
    totalMarks: 177,
  },
  {
    id: 8,
    username: 'liam_martin',
    password: 'liampass',
    name: 'Liam Martin',
    age: 16,
    class: 9,
    marks: {
      math: 92,
      science: 87,
      english: 94,
    },
    totalMarks: 273,
  },
  {
    id: 9,
    username: 'ava_garcia',
    password: 'ava123',
    name: 'Ava Garcia',
    age: 17,
    class: 10,
    marks: {
      math: 68,
      science: 72,
      english: 75,
    },
    totalMarks: 215,
  },
  {
    id: 10,
    username: 'noah_harris',
    password: 'noahpass',
    name: 'Noah Harris',
    age: 18,
    class: 12,
    marks: {
      math: 81,
      science: 79,
      english: 84,
    },
    totalMarks: 244,
  },
];
